const hotels = [
  {
    id: 1,
    name: "The Star Grand Hotel and Residences",
    location: "Sydney, Australia",
    image: "assets/img/hotel1.jpg",
    pricePerNight: 320,
    stars: 5,
    rating: 4.5,
    checkIn: "From 03:00 PM",
    checkOut: "Until 11:00 AM",
    description: [
      "Located in the heart of Sydney, The Star Grand Hotel and Residences offers a sophisticated blend of luxury accommodation and world-class casino entertainment.",
      "Guests enjoy modern, spacious rooms with sweeping views of the Sydney skyline and Darling Harbour.",
      "With award-winning dining, a luxury spa, and direct access to The Star Casino, it’s an ideal destination for both leisure and excitement.",
    ],
    extras: [
      "Direct access to The Star Casino",
      "Luxury spa and wellness center",
      "Award-winning restaurants",
      "Darling Harbour views",
      "Exclusive VIP gaming rooms",
    ],
    amenities: [
      "Free WiFi",
      "Casino",
      "Swimming Pool",
      "Spa & Wellness Center",
      "Fitness Center",
      "Restaurant",
      "Room Service",
      "Parking",
      "Air Conditioning",
      "Non-smoking Rooms",
    ],
  },
  {
    id: 2,
    name: "Crown Towers Melbourne",
    location: "Melbourne, Australia",
    image: "assets/img/hotel2.jpg",
    pricePerNight: 450,
    stars: 5,
    rating: 4.8,
    checkIn: "From 02:00 PM",
    checkOut: "Until 11:00 AM",
    description: [
      "Crown Towers Melbourne is Australia's premier luxury hotel, offering lavish accommodations with sweeping views of the city and Yarra River.",
      "The hotel is part of the Crown Entertainment Complex, home to Australia's largest casino, world-class restaurants, and a luxury shopping precinct.",
      "With impeccable service, Crown Towers sets the standard for luxury stays in Melbourne.",
    ],
    extras: [
      "Access to Crown Casino",
      "Infinity swimming pool",
      "Luxury shopping precinct",
      "Fine dining restaurants",
      "Full-service spa and wellness",
    ],
    amenities: [
      "Free WiFi",
      "Casino",
      "Swimming Pool",
      "Spa & Wellness Center",
      "Fitness Center",
      "Restaurant",
      "Bar",
      "Room Service",
      "Air Conditioning",
      "Non-smoking Rooms",
    ],
  },
  {
    id: 3,
    name: "Treasury Brisbane",
    location: "Brisbane, Australia",
    image: "assets/img/hotel3.jpg",
    pricePerNight: 280,
    stars: 5,
    rating: 4.4,
    checkIn: "From 03:00 PM",
    checkOut: "Until 12:00 PM",
    description: [
      "Treasury Brisbane offers a unique combination of historic architecture and modern luxury in the heart of Brisbane’s CBD.",
      "Housed in two beautifully restored heritage buildings, the hotel provides direct access to the Treasury Casino and its vibrant gaming and entertainment options.",
      "With luxurious accommodations and premium dining experiences, Treasury Brisbane promises an unforgettable stay.",
    ],
    extras: [
      "Historic heritage architecture",
      "Direct access to Treasury Casino",
      "Fine dining restaurants",
      "Central Brisbane location",
      "Boutique shopping nearby",
    ],
    amenities: [
      "Free WiFi",
      "Casino",
      "Restaurant",
      "Fitness Center",
      "Room Service",
      "Air Conditioning",
      "Non-smoking Rooms",
    ],
  },
  {
    id: 4,
    name: "The Ville Resort-Casino",
    location: "Townsville, Australia",
    image: "assets/img/hotel4.jpg",
    pricePerNight: 220,
    stars: 4,
    rating: 4.2,
    checkIn: "From 02:00 PM",
    checkOut: "Until 11:00 AM",
    description: [
      "Overlooking the Coral Sea, The Ville Resort-Casino combines tropical luxury with gaming excitement.",
      "Guests can enjoy newly renovated rooms, infinity pool views, and direct access to the Ville Casino and its entertainment venues.",
      "Located minutes from the Great Barrier Reef ferry terminal, it’s the perfect getaway for adventure and leisure.",
    ],
    extras: [
      "Oceanfront infinity pool",
      "Access to Ville Casino",
      "Great Barrier Reef nearby",
      "Multiple bars and restaurants",
      "Luxury spa services",
    ],
    amenities: [
      "Free WiFi",
      "Casino",
      "Swimming Pool",
      "Restaurant",
      "Spa & Wellness Center",
      "Room Service",
      "Air Conditioning",
      "Non-smoking Rooms",
    ],
  },
  {
    id: 5,
    name: "Lasseters Hotel Casino",
    location: "Alice Springs, Australia",
    image: "assets/img/hotel5.jpg",
    pricePerNight: 190,
    stars: 4,
    rating: 4.0,
    checkIn: "From 02:00 PM",
    checkOut: "Until 11:00 AM",
    description: [
      "Located at the foot of the MacDonnell Ranges, Lasseters Hotel Casino offers a unique desert resort experience in Alice Springs.",
      "The hotel features luxurious accommodations, four restaurants, and a lively casino.",
      "It’s the perfect destination for travelers exploring the Red Centre and seeking entertainment and relaxation.",
    ],
    extras: [
      "Access to Lasseters Casino",
      "Desert resort ambiance",
      "Multiple dining options",
      "Outdoor pool and fitness center",
      "Spa and wellness services",
    ],
    amenities: [
      "Free WiFi",
      "Casino",
      "Swimming Pool",
      "Restaurant",
      "Fitness Center",
      "Room Service",
      "Parking",
      "Air Conditioning",
      "Non-smoking Rooms",
    ],
  },
  {
    id: 6,
    name: "SkyCity Darwin",
    location: "Darwin, Australia",
    image: "assets/img/hotel6.jpg",
    pricePerNight: 310,
    stars: 5,
    rating: 4.3,
    checkIn: "From 03:00 PM",
    checkOut: "Until 12:00 PM",
    description: [
      "Set on the picturesque Mindil Beach, SkyCity Darwin is a tropical oasis offering luxury accommodations and an exciting casino experience.",
      "Guests can enjoy oceanfront rooms, lagoon pools, and fine dining options, all with direct access to SkyCity Casino’s vibrant entertainment.",
      "Perfectly located for exploring Darwin’s attractions, national parks, and beaches.",
    ],
    extras: [
      "Beachfront location",
      "Access to SkyCity Casino",
      "Lagoon-style swimming pools",
      "Award-winning dining",
      "Spa and wellness retreat",
    ],
    amenities: [
      "Free WiFi",
      "Casino",
      "Swimming Pool",
      "Spa & Wellness Center",
      "Restaurant",
      "Fitness Center",
      "Room Service",
      "Parking",
      "Air Conditioning",
      "Non-smoking Rooms",
    ],
  },
];
